3.40a
P(Y = 14)
```{r}
choose(20, 14) * 0.8^14 * 0.2^6
```


3.40b
P(Y ≥ 10)
```{r}
total <- 0
for (k in 10:20) {
  total <- total + choose(20, k) * 0.8^k *0.2^(20-k)
}
total
```

3.40c
P(14 ≤ Y ≤ 18)
```{r}
total <- 0
for (k in 14:18) {
  total <- total + choose(20, k) * 0.8^k *0.2^(20-k)
}
total
```


3.40d
P(Y ≤ 16)
```{r}
total <- 0
for (k in 0:16) {
  total <- total + choose(20, k) * 0.8^k *0.2^(20-k)
}
total
```


3.44a
P(Y = 5)
```{r}
choose(5,5) * 0.8^5 * 0.2^0
```

3.44b
P(Y = 4)
```{r}
choose(5,4) * 0.6^4 * 0.4
```

3.121a
Poisson, λ = 2, find P(Y = 4)
```{r}
(16*exp(-2))/24
```

3.122c
Poisson, λ = 7, find P(Y = 5)
```{r}
(exp(-7)*7^5)/(5*24)
```

3.128
Poisson, λ = 80 per hour = 4/3 per minute, find P(Y ≥ 1)
```{r}
1-exp(-4/3)
```


4.58a
Normal dist
P(0 ≤ Z ≤ 1.2)
```{r}
pnorm(1.2)-pnorm(0)
```
part b
P(-0.9 ≤ Z ≤ 0)
```{r}
pnorm(0) - pnorm(-0.9)
```


4.63a
```{r}
pnorm(17, 16, 1, lower.tail = F)
```

4.66a
```{r}
pnorm(3.002, 3.0005, 0.0010, lower.tail = F) + pnorm(2.998, 3.0005, 0.0010)
```

4.74b
```{r}
qnorm(0.9, 78, 6)
```






